RISCV_ARCH := rv32i
RISCV_ABI := ilp32
RISCV_MCMODEL := medlow


TARGET = vido


#CFLAGS += -DSIMULATION
#CFLAGS += -O2
#ASM_SRCS +=
#LD
C_SFLAGS +=
#INCLUDES += -I.
C_SRCS := \
	main.c \


COMMON_DIR = ..
include ../common.mk
