RISCV_ARCH := rv32im
RISCV_ABI := ilp32
RISCV_MCMODEL := medlow


TARGET = full_complian


#CFLAGS += -DSIMULATION
#CFLAGS += -O2
ASM_SRCS +=main.S
#LD
C_SFLAGS +=
INCLUDES += -I.
#C_SRCS := \



COMMON_DIR = ..
TOOLCHAIN_DIR = ../..
include ../common.mk
